//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucMoiNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long id { get; set; }
        public string user_email { get; set; }
        public string user_name { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> date_id { get; set; }
        public Nullable<long> news_id { get; set; }
        public Nullable<long> post_id { get; set; }
        public string full_content { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> parent_id { get; set; }
    }
}
