//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucMoiNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public long id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public string full_content { get; set; }
        public string image { get; set; }
        public string link { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string keywords { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> date_id { get; set; }
        public string pdf { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> loads { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> parent_id { get; set; }
    }
}
