//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucMoiNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public long id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string url { get; set; }
        public string post_id { get; set; }
        public string message { get; set; }
        public string domain { get; set; }
        public string domain_name { get; set; }
        public string create_time { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<int> date_id { get; set; }
        public string page_id { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public string avatar { get; set; }
        public string date_long { get; set; }
        public string des { get; set; }
        public string full_content { get; set; }
        public string full_link { get; set; }
        public Nullable<int> loads { get; set; }
        public Nullable<int> status { get; set; }
    }
}
