//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucMoiNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public long id { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> date_id { get; set; }
        public string channel { get; set; }
        public Nullable<int> channel_id { get; set; }
        public string id_video { get; set; }
        public string image { get; set; }
    }
}
