//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucMoiNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public long id { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> date_id { get; set; }
        public Nullable<double> wind_chill { get; set; }
        public Nullable<double> wind_direction { get; set; }
        public Nullable<double> wind_speed { get; set; }
        public Nullable<double> atmosphere_humidity { get; set; }
        public Nullable<double> atmosphere_pressure { get; set; }
        public Nullable<double> atmosphere_visibility { get; set; }
        public string astronomy_sunrise { get; set; }
        public string astronomy_sunset { get; set; }
        public string forecast { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<double> temp { get; set; }
        public string name_location { get; set; }
    }
}
